# Place a copy of this config to ~/.aerospace.toml

# You can use it to add commands that run after AeroSpace startup.
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = true

[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0


# Window detection rules for automatic workspace assignment
[[on-window-detected]]
if = { app-id = 'com.valvesoftware.steam' }
run = ['move-node-to-workspace g']

[[on-window-detected]]
if = { app-id = 'com.hnc.Discord' }
run = ['move-node-to-workspace C']

[[on-window-detected]]
if = { app-id = 'company.thebrowser.Browser' }
run = ['move-node-to-workspace B']

[[on-window-detected]]
if = { app-id = 'com.apple.Safari' }
run = ['move-node-to-workspace B']

[[on-window-detected]]
if = { app-name-regex-substring = 'ghostty' }
run = ['move-node-to-workspace S']



[mode.main.binding]
alt-p = "mode project"   # Project selector
alt-shift-semicolon = 'mode service' # Service mode
esc   = "mode main"      # Exit project selector

# Open Terminal https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
alt-enter = '''exec-and-forget osascript -e '
tell application "Ghostty"
    do script
    activate
end tell'
'''

# Checkout later See: https://nikitabobko.github.io/AeroSpace/commands#layout
# alt-h = 'layout tiles horizontal vertical'
# alt-v = 'layout accordion horizontal vertical'

# VIM Focus Movement
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

# Workspace Switcher
alt-tab = 'workspace-back-and-forth' # Switch between workspaces
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-b = 'workspace B' # Browser
alt-c = 'workspace C' # Chat
alt-d = 'workspace D' # Discord
alt-s = 'workspace S' #Shell


# Move to Workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-b = 'move-node-to-workspace B' # Browser
alt-shift-c = 'move-node-to-workspace C' # Chat
alt-shift-d = 'move-node-to-workspace D' # Discord
alt-shift-s = 'move-node-to-workspace S' # Shell


# Move Workspace to Monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# --- SERVICE MODE ---
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = [
    'layout floating tiling',
    'mode main',
] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']
space = ['fullscreen', 'mode main']

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

down = 'volume down'
up = 'volume up'
shift-down = ['volume set 0', 'mode main']


# --- PROJECT A ---
[mode.projA.binding]
1 = "workspace projA-1"
2 = "workspace projA-2"
3 = "workspace projA-3"
shift-1 = ["move-node-to-workspace projA-1", "workspace projA-1"]
shift-2 = ["move-node-to-workspace projA-2", "workspace projA-2"]
shift-3 = ["move-node-to-workspace projA-3", "workspace projA-3"]
ctrl-esc = "mode main"

# --- PROJECT B ---
[mode.projB.binding]
1 = "workspace projB-1"
2 = "workspace projB-2"
3 = "workspace projB-3"
shift-1 = ["move-node-to-workspace projB-1", "workspace projB-1"]
shift-2 = ["move-node-to-workspace projB-2", "workspace projB-2"]
shift-3 = ["move-node-to-workspace projB-3", "workspace projB-3"]
esc = "mode main"


# --- PROJECT C ---
[mode.projC.binding]
1 = "workspace projC-1"
2 = "workspace projC-2"
3 = "workspace projC-3"
shift-1 = ["move-node-to-workspace projC-1", "workspace projC-1"]
shift-2 = ["move-node-to-workspace projC-2", "workspace projC-2"]
shift-3 = ["move-node-to-workspace projC-3", "workspace projC-3"]
esc = "mode main"

# --- PROJECT SELECTOR ---
[mode.project.binding]
d = ["mode default", "workspace default-s"]  # enter default context
a = ["mode projA",   "workspace projA-s"]    # enter projA context
b = ["mode projB",   "workspace projB-s"]    # enter projB context
c = ["mode projC",   "workspace projC-s"]    # enter projC context
esc = "mode main"